[cours]
[cours.Lundi20h00AkBaroqueadulte]
    jour = "Lundi"
    heure = "20h00"
    prof = "Anouk"
    discipline = "Baroque"
    niveau = "Adulte"
    nombre_eleves = 10
    gala = 1
    ordre_gala = 2
    nb_garcons = 0
    duree = "03:00"
[cours.Mardi17h30ACJazzC2]
    jour = 'Mardi'
    heure = '17h30'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C2'
    nombre_eleves = 12
    gala = 3
    ordre_gala = 3
    nb_garcons = 0
    duree = "03:00"
[cours.Mardi17h30AnClassiqueC1P3C2P0P1]
    jour = 'Mardi'
    heure = '17h30'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = ' C1 P3 - C2 P0/P1'
    nombre_eleves = 18
    gala = 3
    ordre_gala = 2
    nb_garcons = 0
    duree = "03:00"
[cours.Mardi18h30ACJazz18h30ACC3Inter]
    jour = 'Mardi'
    heure = '18h30'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C3 Inter'
    nombre_eleves = 10
    gala = 3
    ordre_gala = 4
    nb_garcons = 0
    duree = "03:00"
[cours.Mercredi09h30AnEveil]
    jour = 'Mercredi'
    heure = '09h30'
    prof = 'Angélique'
    discipline = 'Eveil/Initiation'
    niveau = ' Eveil'
    nombre_eleves = 10
    gala = 3
    ordre_gala = 5
    nb_garcons = 0
    duree = "03:00"
[cours.Mercredi10h30AdInitiation]
    jour = 'Mercredi'
    heure = '10h30'
    prof = 'Adeline'
    discipline = 'Eveil/Initiation'
    niveau = 'Initiation'
    nombre_eleves = 20
    gala = 2
    ordre_gala = 7
    nb_garcons = 0
    duree = "02:27"
[cours.Mercredi10h30MaJazzC1P1P2]
    jour = 'Mercredi'
    heure = '10h30'
    prof = 'Maëliss'
    discipline = 'Jazz'
    niveau = ' C1 P1/P2'
    nombre_eleves = 8
    gala = 3
    ordre_gala = 9
    nb_garcons = 0
    duree = "03:00"
[cours.Mercredi10h30MDClassiqueC1P3C2P0P1]
    jour = 'Mercredi'
    heure = '10h30'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = ' C1 P3 - C2 P0/P1'
    nombre_eleves = 10
    gala = 3
    ordre_gala = 8
    nb_garcons = 0
    duree = "03:00"
[cours.Mercredi11h30AdClassiqueC1P2P3]
    jour = 'Mercredi'
    heure = '11h30'
    prof = 'Adeline'
    discipline = 'Classique'
    niveau = 'C1 P2/P3'
    nombre_eleves = 7
    gala = 3
    ordre_gala = 10
    nb_garcons = 0
    duree = "03:00"
[cours.Mercredi11h30AnClassiqueC1P0]
    jour = 'Mercredi'
    heure = '11h30'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C1 P0'
    nombre_eleves = 17
    gala = 3
    ordre_gala = 10
    nb_garcons = 0
    duree = 0
[cours.Mercredi11h30ElClassiqueC1P1P2]
    jour = 'Mercredi'
    heure = '11h30'
    prof = 'Elaura'
    discipline = 'Classique'
    niveau = ' C1 P1/P2'
    nombre_eleves = 16
    gala = 3
    ordre_gala = 12
    nb_garcons = 0
    duree = 0
[cours.Mercredi11h30MaJazzC1P3C2P0]
    jour = 'Mercredi'
    heure = '11h30'
    prof = 'Maëliss'
    discipline = 'Jazz'
    niveau = 'C1 P3/C2 P0'
    nombre_eleves = 6
    gala = 3
    ordre_gala = 13
    nb_garcons = 0
    duree = 0
[cours.Mercredi13h45AnClassiqueC1P3C2P0]
    jour = 'Mercredi'
    heure = '13h45'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C1 P3 - C2 P0'
    nombre_eleves = 14
    gala = 2
    ordre_gala = 3
    nb_garcons = 0
    duree = 0
[cours.Mercredi13h45MDClassiqueC2P1P2P3]
    jour = 'Mercredi'
    heure = '13h45'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = 'C2 P1/P2/P3'
    nombre_eleves = 22
    gala = 2
    ordre_gala = 4
    nb_garcons = 0
    duree = 0
[cours.Mercredi13h45ACJazzC2]
    jour = 'Mercredi'
    heure = '13h45'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = ' C2'
    nombre_eleves = 9
    gala = 2
    ordre_gala = 6
    nb_garcons = 0
    duree = 0
[cours.Mercredi13h45ElClassiqueC1P1P2]
    jour = 'Mercredi'
    heure = '13h45'
    prof = 'Elaura'
    discipline = 'Classique'
    niveau = 'C1 P1/P2'
    nombre_eleves = 14
    gala = 2
    ordre_gala = 2
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45AnClassiqueC1P0P1]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C1 P0/P1'
    nombre_eleves = 16
    gala = 2
    ordre_gala = 9
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45MDClassiqueC3Inter]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = ' C3 Inter'
    nombre_eleves = 18
    gala = 2
    ordre_gala = 10
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45SiCaractereC2C3]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Sirarpik'
    discipline = 'Caractère'
    niveau = "C2 C3"
    nombre_eleves = 5
    gala = 2
    ordre_gala = 12
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45AdEveil]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Adeline'
    discipline = 'Eveil'
    niveau = 'Eveil'
    nombre_eleves = 18
    gala = 2
    ordre_gala = 8
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45ACJazzC2]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C2'
    nombre_eleves = 16
    gala = 2
    ordre_gala = 13
    nb_garcons = 0
    duree = 0
[cours.Mercredi14h45MaJazzC1]
    jour = 'Mercredi'
    heure = '14h45'
    prof = 'Maëliss'
    discipline = 'Jazz'
    niveau = 'C1'
    nombre_eleves = 18
    gala = 2
    ordre_gala = 14
    nb_garcons = 0
    duree = 0
[cours.Mercredi15h45AnInitiation]
    jour = 'Mercredi'
    heure = '15h45'
    prof = 'Angélique'
    discipline = 'Initiation'
    niveau = 'Initiation'
    nombre_eleves = 8
    gala = 2
    ordre_gala = 16
    nb_garcons = 0
    duree = 0
[cours.Mercredi15h45ElClassiqueC1P0P1]
    jour = 'Mercredi'
    heure = '15h45'
    prof = 'Elaura'
    discipline = 'Classique'
    niveau = 'C1 P0/P1'
    nombre_eleves = 14
    gala = 2
    ordre_gala = 15
    nb_garcons = 0
    duree = 0
[cours.Mercredi16h00ACJazzC3Inter]
    jour = 'Mercredi'
    heure = '16h00'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C3 Inter'
    nombre_eleves = 16
    gala = 2
    ordre_gala = 17
    nb_garcons = 0
    duree = 0
[cours.Mercredi16h45MLClassiqueC1P3C2P0P1]
    jour = 'Mercredi'
    heure = '16h45'
    prof = 'Marie-Line'
    discipline = 'Classique'
    niveau = 'C1 P3 - C2 P0/P1'
    nombre_eleves = 11
    gala = 2
    ordre_gala = 20
    nb_garcons = 0
    duree = 0
[cours.Mercredi16h45MaJazzC2]
    jour = 'Mercredi'
    heure = '16h45'
    prof = 'Maëliss'
    discipline = 'Jazz'
    niveau = ' C2'
    nombre_eleves = 13
    gala = 2
    ordre_gala = 18
    nb_garcons = 0
    duree = 0
[cours.Mercredi17h45MLClassiqueC2P2P3]
    jour = 'Mercredi'
    heure = '17h45'
    prof = 'Marie-Line'
    discipline = 'Classique'
    niveau = 'C2 P2/P3'
    nombre_eleves = 15
    gala = 2
    ordre_gala = 21
    nb_garcons = 0
    duree = 0
[cours.Mercredi17h45MaJazzC3Avance]
    jour = 'Mercredi'
    heure = '17h45'
    prof = 'Maëliss'
    discipline = 'Jazz'
    niveau = 'C3 Avancé'
    nombre_eleves = 12
    gala = 2
    ordre_gala = 22
    nb_garcons = 0
    duree = 0
[cours.Mercredi18h45ACContemporainC2C3]
    jour = 'Mercredi'
    heure = '18h45'
    prof = 'Anne-Charlotte'
    discipline = 'Contemporain'
    niveau = 'C2 C3'
    nombre_eleves = 18
    gala = 2
    ordre_gala = 23
    nb_garcons = 0
    duree = 0
[cours.Mercredi18h45MDClassiqueC3Avance]
    jour = 'Mercredi'
    heure = '18h45'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = 'C3 Avancé'
    nombre_eleves = 14
    gala = 3
    ordre_gala = 22
    nb_garcons = 0
    duree = 0
[cours.Vendredi17h30ElClassiqueC1P2P3]
    jour = 'Vendredi'
    heure = '17h30'
    prof = 'Elaura'
    discipline = 'Classique'
    niveau = 'C1 P2/P3'
    nombre_eleves = 11
    gala = 3
    ordre_gala = 16
    nb_garcons = 0
    duree = 0
[cours.Vendredi17h30AnClassiqueC1P0P1]
    jour = 'Vendredi'
    heure = '17h30'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C1 P0/P1'
    nombre_eleves = 17
    gala = 3
    ordre_gala = 15
    nb_garcons = 0
    duree = 0
[cours.Vendredi18h00EleoContemporainC3]
    jour = 'Vendredi'
    heure = '18h00'
    prof = 'Eleonora'
    discipline = 'Contemporain'
    niveau = 'C3'
    nombre_eleves = 16
    gala = 3
    ordre_gala = 18
    nb_garcons = 0
    duree = 0
[cours.Vendredi18h30AnClassiqueC3Inter]
    jour = 'Vendredi'
    heure = '18h30'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C3 Inter'
    nombre_eleves = 12
    gala = 3
    ordre_gala = 20
    nb_garcons = 0
    duree = 0
[cours.Vendredi18h30MDClassiqueC3Avance]
    jour = 'Vendredi'
    heure = '18h30'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = 'C3 Avancé'
    nombre_eleves = 8
    gala = 3
    ordre_gala = 21
    nb_garcons = 0
    duree = 0
[cours.Samedi09h15AnEveil]
    jour = 'Samedi'
    heure = '09h15'
    prof = 'Angélique'
    discipline = 'Eveil'
    niveau = 'Eveil'
    nombre_eleves = 10
    gala = 1
    ordre_gala = 3
    nb_garcons = 0
    duree = 0
[cours.Samedi09h30VaClassiqueC1P2]
    jour = 'Samedi'
    heure = '09h30'
    prof = 'Valentine'
    discipline = 'Classique'
    niveau = 'C1 P2'
    nombre_eleves = 12
    gala = 1
    ordre_gala = 4
    nb_garcons = 0
    duree = 0
[cours.Samedi09h30MDClassiqueC2P2P3]
    jour = 'Samedi'
    heure = '09h30'
    prof = 'Marie-Danielle'
    discipline = 'Classique'
    niveau = 'C2 P2/P3'
    nombre_eleves = 22
    gala = 1
    ordre_gala = 5
    nb_garcons = 0
    duree = 0
[cours.Samedi09h30AlClassiqueC1P0]
    jour = 'Samedi'
    heure = '09h30'
    prof = 'Almendra'
    discipline = 'Classique'
    niveau = 'C1 P0'
    nombre_eleves = 9
    gala = 1
    ordre_gala = 6
    nb_garcons = 0
    duree = 0
[cours.Samedi09h30ACJazzC1]
    jour = 'Samedi'
    heure = '09h30'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C1'
    nombre_eleves = 9
    gala = 1
    ordre_gala = 7
    nb_garcons = 0
    duree = 0
[cours.Samedi10h15AnClassiqueC3Inter]
    jour = 'Samedi'
    heure = '10h15'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C3 Inter'
    nombre_eleves = 23
    gala = 1
    ordre_gala = 9
    nb_garcons = 0
    duree = 0
[cours.Samedi10h30AlInitiation]
    jour = 'Samedi'
    heure = '10h30'
    prof = 'Almendra'
    discipline = 'Eveil/Initiation'
    niveau = ' Initiation'
    nombre_eleves = 16
    gala = 1
    ordre_gala = 12
    nb_garcons = 0
    duree = 0
[cours.Samedi10h30LoClassiqueC1P2P3]
    jour = 'Samedi'
    heure = '10h30'
    prof = 'Louise'
    discipline = 'Classique'
    niveau = 'C1 P2/P3'
    nombre_eleves = 17
    gala = 1
    ordre_gala = 13
    nb_garcons = 0
    duree = 0
[cours.Samedi10h30VaClassiqueC1P0P1]
    jour = 'Samedi'
    heure = '10h30'
    prof = 'Valentine'
    discipline = 'Classique'
    niveau = 'C1 P0/P1'
    nombre_eleves = 18
    gala = 1
    ordre_gala = 10
    nb_garcons = 0
    duree = 0
[cours.Samedi10h30ACJazzC2]
    jour = 'Samedi'
    heure = '10h30'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C2'
    nombre_eleves = 24
    gala = 1
    ordre_gala = 14
    nb_garcons = 0
    duree = 0
[cours.Samedi11h30LoClassiqueC2P0P1]
    jour = 'Samedi'
    heure = '11h30'
    prof = 'Louise'
    discipline = 'Classique'
    niveau = 'C2 P0/P1'
    nombre_eleves = 15
    gala = 1
    ordre_gala = 20
    nb_garcons = 0
    duree = 0
[cours.Samedi11h30AlClassiqueC1P3C2P0]
    jour = 'Samedi'
    heure = '11h30'
    prof = 'Almendra'
    discipline = 'Classique'
    niveau = ' C1 P3 - C2 P0'
    nombre_eleves = 14
    gala = 1
    ordre_gala = 19
    nb_garcons = 0
    duree = 0
[cours.Samedi11h30AnClassiqueC1P1P2]
    jour = 'Samedi'
    heure = '11h30'
    prof = 'Angélique'
    discipline = 'Classique'
    niveau = 'C1 P1/P2'
    nombre_eleves = 14
    gala = 1
    ordre_gala = 15
    nb_garcons = 0
    duree = 0
[cours.Samedi11h30ACJazzC3Inter]
    jour = 'Samedi'
    heure = '11h30'
    prof = 'Anne-Charlotte'
    discipline = 'Jazz'
    niveau = 'C3 Inter'
    nombre_eleves = 18
    gala = 1
    ordre_gala = 22
    nb_garcons = 0
    duree = 0
[cours.AdulteDixitDominusMD]
    jour = "Mercredi"
    heure = "20h00"
    prof = "Marie-Danielle"
    discipline = "Classique"
    niveau = "Adulte"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 21
    nb_garcons = 0
    duree = 0
[cours.HALyceeChansondeSolveig]
    jour = ""
    heure = ""
    prof = ""
    discipline = ""
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 8
    nb_garcons = 0
    duree = 0
[cours.HACollegeCaractereTarentelle]
    jour = ""
    heure = ""
    prof = "Sirarpik"
    discipline = "Caractère"
    niveau = "HA Collège"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 11
    nb_garcons = 0
    duree = 0
[cours.HACollegeClassiqueAnAd]
    jour = ""
    heure = ""
    prof = ""
    discipline = "Classique"
    niveau = "HA Collège"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 16
    nb_garcons = 0
    duree = 0
[cours.HALyceeContemporainVidarRoidelaMontagne]
    jour = ""
    heure = ""
    prof = ""
    discipline = "Contemporain"
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 17
    nb_garcons = 0
    duree = 0
[cours.HALyceeClassiqueWeberInvitationalavalse]
    jour = ""
    heure = ""
    prof = ""
    discipline = "Classique"
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 1
    ordre_gala = 23
    nb_garcons = 0
    duree = 0
[cours.HALyceeContemporainACMe]
    jour = "Mercredi"
    heure = ""
    prof = "Anne-Charlotte"
    discipline = "Contemporain"
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 2
    ordre_gala = 7
    nb_garcons = 0
    duree = 0
[cours.HACollegeNeoclassiqueMD]
    jour = ""
    heure = ""
    prof = "Marie-Danielle"
    discipline = "Classique"
    niveau = "HA Collège"
    nombre_eleves = 0
    gala = 2
    ordre_gala = 11
    nb_garcons = 0
    duree = 0
[cours.HACollegeCaractereTzigane]
    jour = ""
    heure = ""
    prof = "Sirarpik"
    discipline = "Caractère"
    niveau = "HA Collège"
    nombre_eleves = 0
    gala = 2
    ordre_gala = 19
    nb_garcons = 0
    duree = 0
[cours.HACollegeLyceeCharleston]
    jour = ""
    heure = ""
    prof = ""
    discipline = ""
    niveau = "HA Collège Lycée"
    nombre_eleves = 0
    gala = 2
    ordre_gala = 24
    nb_garcons = 0
    duree = 0
[cours.HACollegeContemporainAC]
    jour = ""
    heure = ""
    prof = "Anne-Charlotte"
    discipline = ""
    niveau = "HA Collège Lycée"
    nombre_eleves = 0
    gala = 3
    ordre_gala = 6
    nb_garcons = 0
    duree = 0
[cours.HALyceeContemporainVidarDanseAnitra]
    jour = ""
    heure = ""
    prof = ""
    discipline = "Contemporain"
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 3
    ordre_gala = 14
    nb_garcons = 0
    duree = 0
[cours.HACollegeContemporainVidarRevoltedesEnfants]
    jour = ""
    heure = ""
    prof = ""
    discipline = ""
    niveau = "HA Collège"
    nombre_eleves = 0
    gala = 3
    ordre_gala = 17
    nb_garcons = 0
    duree = 0
[cours.HALyceeLaLaLand]
    jour = ""
    heure = ""
    prof = ""
    discipline = "Jazz"
    niveau = "HA Lycée"
    nombre_eleves = 0
    gala = 3
    ordre_gala = 19
    nb_garcons = 0
    duree = 0